#!/usr/bin/env zsh


# Check if a commit message is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 'commit message'"
    exit 1
fi


# Capture the commit message
COMMIT_MESSAGE="$1"
 

# Execute the npx command
npx --yes -- single-page-markdown-website '*.md'

# Move the built index.html to docs. The reason this
# had to be done is that, at least when I was trying
# to set this Pages site up, Pages only let me choose
# the root or docs directories for the site. Those are
# all that showed up in the menu, even if the project
# had no docs directory.
mv build/index.html docs

git commit -a -m "$COMMIT_MESSAGE"

git push